import { IProductData } from '../types/IProductData'

export const productData: IProductData[] = [
  {
    name: 'Item 1',
    category: 'Yarn',
    brand: 'Macrametr',
    description: '',
    price: 1,
    stock: 1,
    photo: '',
  },
  {
    name: 'Item 2',
    category: 'Yarn',
    brand: 'Macrametr',
    description: '',
    price: 1,
    stock: 1,
    photo: '',
  },
  {
    name: 'Item 3',
    category: 'Yarn',
    brand: 'Macrametr',
    description: '',
    price: 1,
    stock: 1,
    photo: '',
  },
  {
    name: 'Item 4',
    category: 'Yarn',
    brand: 'Macrametr',
    description: '',
    price: 1,
    stock: 1,
    photo: '',
  },
  {
    name: 'Item 5',
    category: 'Yarn',
    brand: 'Macrametr',
    description: '',
    price: 1,
    stock: 1,
    photo: '',
  },
  {
    name: 'Item 6',
    category: 'Yarn',
    brand: 'Macrametr',
    description: '',
    price: 1,
    stock: 1,
    photo: '',
  },
  {
    name: 'Item 7',
    category: 'Yarn',
    brand: 'Macrametr',
    description: '',
    price: 1,
    stock: 1,
    photo: '',
  },
  {
    name: 'Item 8',
    category: 'Yarn',
    brand: 'Macrametr',
    description: '',
    price: 1,
    stock: 1,
    photo: '',
  },
  {
    name: 'Item 9',
    category: 'Beads',
    brand: 'Gamma',
    description: '',
    price: 2,
    stock: 1,
    photo: '',
  },
  {
    name: 'Item 10',
    category: 'Beads',
    brand: 'Gamma',
    description: '',
    price: 2,
    stock: 1,
    photo: '',
  },
  {
    name: 'Item 11',
    category: 'Beads',
    brand: 'Gamma',
    description: '',
    price: 2,
    stock: 1,
    photo: '',
  },
  {
    name: 'Item 12',
    category: 'Beads',
    brand: 'Gamma',
    description: '',
    price: 2,
    stock: 1,
    photo: '',
  },
  {
    name: 'Item 13',
    category: 'Beads',
    brand: 'Gamma',
    description: '',
    price: 2,
    stock: 1,
    photo: '',
  },
  {
    name: 'Item 14',
    category: 'Beads',
    brand: 'Gamma',
    description: '',
    price: 2,
    stock: 1,
    photo: '',
  },
  {
    name: 'Item 15',
    category: 'Beads',
    brand: 'Gamma',
    description: '',
    price: 2,
    stock: 1,
    photo: '',
  },
  {
    name: 'Item 16',
    category: 'Beads',
    brand: 'Gamma',
    description: '',
    price: 2,
    stock: 1,
    photo: '',
  },
  {
    name: 'Item 17',
    category: 'Paint',
    brand: 'Preciosa',
    description: '',
    price: 1,
    stock: 1,
    photo: '',
  },
  {
    name: 'Item 18',
    category: 'Paint',
    brand: 'Preciosa',
    description: '',
    price: 1,
    stock: 1,
    photo: '',
  },
  {
    name: 'Item 19',
    category: 'Paint',
    brand: 'Preciosa',
    description: '',
    price: 1,
    stock: 1,
    photo: '',
  },
  {
    name: 'Item 20',
    category: 'Paint',
    brand: 'Preciosa',
    description: '',
    price: 1,
    stock: 1,
    photo: '',
  },
  {
    name: 'Item 21',
    category: 'Paint',
    brand: 'Preciosa',
    description: '',
    price: 1,
    stock: 1,
    photo: '',
  },
  {
    name: 'Item 22',
    category: 'Paint',
    brand: 'Preciosa',
    description: '',
    price: 1,
    stock: 1,
    photo: '',
  },
  {
    name: 'Item 23',
    category: 'Paint',
    brand: 'Preciosa',
    description: '',
    price: 1,
    stock: 1,
    photo: '',
  },
  {
    name: 'Item 24',
    category: 'Paint',
    brand: 'Preciosa',
    description: '',
    price: 1,
    stock: 1,
    photo: '',
  },
  {
    name: 'Item 25',
    category: 'Colored Pencils',
    brand: 'Derwent',
    description: '',
    price: 2,
    stock: 1,
    photo: '',
  },
  {
    name: 'Item 26',
    category: 'Colored Pencils',
    brand: 'Derwent',
    description: '',
    price: 2,
    stock: 1,
    photo: '',
  },
  {
    name: 'Item 27',
    category: 'Colored Pencils',
    brand: 'Derwent',
    description: '',
    price: 2,
    stock: 1,
    photo: '',
  },
  {
    name: 'Item 28',
    category: 'Colored Pencils',
    brand: 'Derwent',
    description: '',
    price: 2,
    stock: 1,
    photo: '',
  },
  {
    name: 'Item 29',
    category: 'Colored Pencils',
    brand: 'Derwent',
    description: '',
    price: 2,
    stock: 1,
    photo: '',
  },
  {
    name: 'Item 30',
    category: 'Colored Pencils',
    brand: 'Derwent',
    description: '',
    price: 2,
    stock: 1,
    photo: '',
  },
  {
    name: 'Item 31',
    category: 'Colored Pencils',
    brand: 'Derwent',
    description: '',
    price: 2,
    stock: 1,
    photo: '',
  },
  {
    name: 'Item 32',
    category: 'Colored Pencils',
    brand: 'Derwent',
    description: '',
    price: 2,
    stock: 1,
    photo: '',
  },
]